- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Configure nginx
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Restart nginx
  service:
    name: nginx
    state: restarted
